version: "3.7"

services:
  bingsoo:
    build: .
    image: bingsoo:latest
    ports:
      - 8080:8080
    env_file: ./.env
    environment:
      CONCURRENCY: 4
      PORT: 8080
      DATABASE_URL: postgres://bingsoo:bingsoo@postgres:5432/bingsoo?sslmode=disable
      REDIS_URL: redis://redis:6379

  postgres:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bingsoo
      POSTGRES_PASSWORD: bingsoo
      POSTGRES_USER: bingsoo

  postgres.init:
    image: migrate/migrate:v4.11.0
    entrypoint:
      - wait-for
      - postgres:5432
      - --
      - /run-migrations.sh
    environment:
      DATABASE_URL: postgres://bingsoo:bingsoo@postgres:5432/bingsoo?sslmode=disable
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
      - ./databases/postgres/migrations:/migrations
      - ./databases/postgres/run-migrations.sh:/run-migrations.sh

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
