name: bingsoo

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-bingsoo-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-bingsoo-

      - name: Inject environment
        run: touch .env

      - name: Install dependencies
        run: |
          go mod tidy
          git diff --exit-code --name-only

      - name: Lint
        run: |
          make format
          git diff --exit-code --name-only

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build

      - name: Build image
        run: make image
